# This playbook prints a simple debug message
- name: Deploy VM 
  hosts: all
  connection: local


  tasks:

    # - name: Include task list in play
    #   ansible.builtin.include_tasks: clone_rest.yml


  - name: Print debug message
    debug:
      msg: "Var1 was {{var1}} and var2 was {{var2}}"



  # - name: Create a virtual machine from a template
  #   community.vmware.vmware_guest:
  #     hostname: "{{ vcenter_hostname }}"
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     datacenter: "{{datacenter}}"
  #     cluster: "{{cluster}}"
  #     resource_pool: "{{resource_pool}}"
  #     folder: "{{ folder }}"
  #     name: "{{ inventory_hostname }}"
  #     state: present
  #     template: "{{ vm_template }}"
  #     # disk:
  #     # - size_gb: "{{ disk1_size }}"
  #     #   type: thin
  #     #   datastore: "{{ datastore }}"
  #     # Add another disk from an existing VMDK
  #     hardware:
  #       memory_mb: "{{ ram }}"
  #       num_cpus: "{{ cpus }}"
  #     networks:
  #     - name: "{{nic1_portgroup}}"
  #       device_type: vmxnet3
  #     validate_certs: "{{ vcenter_validate_certs }}"
  #   delegate_to: localhost
  #   when: 
  #     - deploy

  # - name: Undeploy VM
  #   community.vmware.vmware_guest:
  #     hostname: "{{ vcenter_hostname }}"
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     datacenter: "{{datacenter}}"
  #     cluster: "{{cluster}}"
  #     resource_pool: "{{resource_pool}}"
  #     folder: "{{ folder }}"
  #     name: "{{ inventory_hostname }}"
  #     state: absent
  #     validate_certs: "{{ vcenter_validate_certs }}"
  #   delegate_to: localhost
  #   when: 
  #     - deploy != true
